# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_version', models.FloatField(default=0.1)),
                ('api_host', models.CharField(default='https://stepik.org', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
