# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicontroller',
            name='base_url',
        ),
    ]
