# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_controller', '0002_remove_apicontroller_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicontroller',
            name='api_host',
            field=models.CharField(default='https://stepik.org', max_length=255),
        ),
        migrations.AddField(
            model_name='apicontroller',
            name='api_version',
            field=models.FloatField(default=0.1),
        ),
    ]
