# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_change_on_delete_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationservice',
            old_name='created_at',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='translationservice',
            old_name='updated_at',
            new_name='update_date',
        ),
    ]
