# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_add_lesson_uniqueness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translatedstep',
            options={'ordering': ['stepik_id']},
        ),
    ]
