# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_add_step_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedstep',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
