# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0006_translatedstep_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepik_id', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('stepik_update_date', models.DateTimeField()),
                ('service_name', models.CharField(max_length=40)),
                ('steps_count', models.IntegerField(default=0)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='translation.TranslatedLesson')),
            ],
        ),
    ]
