# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 09:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import enumfields.fields
import translation.models.translation


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0010_add_ordering_by_stepik_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedStepSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepik_id', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('stepik_update_date', models.DateTimeField()),
                ('service_name', models.CharField(max_length=40)),
                ('lang', models.CharField(max_length=10)),
                ('type', enumfields.fields.EnumIntegerField(enum=translation.models.translation.StepSource)),
                ('source', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['stepik_id'],
                'abstract': False,
            },
        ),
    ]
