# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_controller', '0001_api_controller'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepik_id', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('stepik_update_date', models.DateTimeField()),
                ('service_name', models.CharField(max_length=40)),
                ('steps_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepik_id', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('stepik_update_date', models.DateTimeField()),
                ('lang', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('service_name', models.CharField(max_length=40)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='translation.TranslatedLesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranslationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=40, unique=True)),
                ('base_url', models.CharField(max_length=255)),
                ('api_version', models.FloatField()),
                ('translated_symbols', models.IntegerField(default=0)),
                ('count_steps', models.IntegerField(default=0)),
                ('api_controller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translation_services', to='api_controller.ApiController')),
            ],
        ),
    ]
