# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatedLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lang', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('service_name', models.CharField(max_length=40)),
                ('stepik_id', models.IntegerField()),
                ('translated_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranslationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepik_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lang', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('service_name', models.CharField(max_length=40)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='translation.TranslatedLesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YandexTranslator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_services', to='api_controller.ApiController')),
            ],
        ),
    ]
