# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationservice',
            name='api_controller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='translation_services', to='api_controller.ApiController'),
        ),
    ]
