# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatedlesson',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='translatedlesson',
            name='text',
        ),
        migrations.RemoveField(
            model_name='translatedlesson',
            name='translated_json',
        ),
    ]
