# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_auto_20170712_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedlesson',
            name='amount_steps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
