# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_translatedlesson_amount_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=40)),
                ('base_url', models.CharField(max_length=255)),
                ('api_version', models.FloatField()),
                ('api_key', models.CharField(max_length=255)),
                ('translated_symbols', models.IntegerField()),
                ('count_steps', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='yandextranslator',
            name='api_controller',
        ),
        migrations.AlterField(
            model_name='translatedlesson',
            name='amount_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='YandexTranslator',
        ),
    ]
