# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_controller', '0002_remove_apicontroller_base_url'),
        ('translation', '0005_auto_20170725_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationservice',
            name='api_controller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translation_services', to='api_controller.ApiController'),
        ),
        migrations.AlterField(
            model_name='translationservice',
            name='count_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='translationservice',
            name='translated_symbols',
            field=models.IntegerField(default=0),
        ),
    ]
