# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0007_auto_20170725_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationstep',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='translation.TranslatedLesson'),
        ),
    ]
