# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0007_translatedcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatedcourse',
            name='lessons',
        ),
        migrations.AddField(
            model_name='translatedlesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='translation.TranslatedCourse'),
        ),
    ]
