# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0008_auto_20170728_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translatedlesson',
            old_name='created_at',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='translatedlesson',
            old_name='amount_steps',
            new_name='steps_count',
        ),
        migrations.RenameField(
            model_name='translatedlesson',
            old_name='updated_at',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='translationstep',
            old_name='created_at',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='translationstep',
            old_name='updated_at',
            new_name='update_date',
        ),
        migrations.AddField(
            model_name='translatedlesson',
            name='stepik_update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 8, 58, 18, 252238)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translationstep',
            name='stepik_update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 8, 58, 35, 259935)),
            preserve_default=False,
        ),
    ]
